FROM node:20-alpine

WORKDIR /app

# Установка зависимостей для тестирования
RUN apk add --no-cache postgresql-client

# Копирование package.json и yarn.lock
COPY package*.json ./
COPY yarn.lock ./

# Установка зависимостей
RUN npm ci

# Копирование исходного кода
COPY . .

# Создание пользователя для безопасности
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nestjs -u 1001

# Изменение владельца файлов
RUN chown -R nestjs:nodejs /app
USER nestjs

# Команда по умолчанию для тестирования
CMD ["npm", "run", "test:all"]
