export const ORDERS_CONSTANTS = {
  SUCCESS: {
    ORDER_CREATED: 'Заказ успешно создан',
    ORDER_UPDATED: 'Заказ успешно обновлен',
    ORDER_STATUS_UPDATED: 'Статус заказа обновлен',
    ORDER_CANCELLED: 'Заказ отменен',
    ORDERS_LOADED: 'Заказы загружены',
    ORDER_FOUND: 'Заказ найден',
    STATISTICS_LOADED: 'Статистика загружена',
    SEARCH_COMPLETED: 'Поиск завершен',
  },
  ERRORS: {
    ORDER_NOT_FOUND: 'Заказ не найден',
    USER_NOT_FOUND: 'Пользователь не найден',
    INVALID_STATUS_TRANSITION: 'Недопустимый переход статуса',
    ORDER_CANNOT_BE_EDITED: 'Заказ нельзя редактировать',
    EMPTY_ORDER: 'Заказ должен содержать товары',
    TOO_MANY_ITEMS: 'Заказ не может содержать более 50 товаров',
    DUPLICATE_ITEMS: 'Заказ содержит дублирующиеся товары',
    INVALID_ITEM_DATA: 'Некорректные данные товара',
    INVALID_PHONE: 'Некорректный номер телефона',
    ADDRESS_TOO_LONG: 'Адрес слишком длинный',
    COMMENT_TOO_LONG: 'Комментарий слишком длинный',
    INVALID_PAGINATION: 'Некорректные параметры пагинации',
    SEARCH_QUERY_TOO_SHORT:
      'Поисковый запрос должен содержать минимум 2 символа',
  },
  VALIDATION: {
    MIN_ITEMS: 1,
    MAX_ITEMS: 50,
    MAX_QUANTITY: 100,
    MAX_ADDRESS_LENGTH: 500,
    MAX_PHONE_LENGTH: 20,
    MAX_COMMENT_LENGTH: 1000,
    MAX_PROMOCODE_LENGTH: 50,
    MIN_SEARCH_QUERY_LENGTH: 2,
    MAX_PAGE_SIZE: 100,
  },
  STATUS_TRANSITIONS: {
    PENDING: ['PAID', 'CANCELLED'],
    PAID: ['SHIPPED', 'CANCELLED'],
    SHIPPED: ['DELIVERED', 'CANCELLED'],
    DELIVERED: [],
    CANCELLED: [],
  },
} as const;
